version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mern-task
      - APP_PORT=5000
      - JWT_SECRET=secret
      - APP_ENV=development
    ports:
      - "4747:5000"
    depends_on:
      - mongo
    networks:
      - app-network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: on-failure

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    restart: on-failure

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
